### ISSUE TITLE
Red, yellow and green mod errors

### ISSUE THREAD

**Issue by carriontrooper** [Giulian7/DeCiv-Reworked#1]
These are the errors that show up in the 'locate mod errors'.

Red errors:
Irrigation System's unique "[+ 1 gold, +0.5 food] from [Farm] tiles [in this city]" contains parameter + 1 gold, +0.5 food, which does not fit parameter type stats !

That space between + and 1 needs to go, and if I recall correctly, you can't put fractions/floats on stats.

Yellow errors:
The Confederacy's unique "[-1 Science] per turn from cities before [Writing]" is deprecated as of 3.18.14, replace with "[stats] [in all cities] <before discovering [tech]>", "[stats] [in all cities] <before adopting [policy]>"

This one is straightforward, replace the unique with "[-1 Science] [in all cities] <before discovering [Writing]>".

Green errors:
Irrigation System's unique "Must be next to [Fresh water] tiles" looks like it may be a misspelling of:
	"Must be next to [terrainFilter]"

Another straightforward one. "Must be next to [Fresh water]".

Also, check out this page for the list of uniques:
https://yairm210.github.io/Unciv/Modders/uniques/

**Comment by Giulian7** [comment]
For now should be ok, thanks
